on:
  - push
  - workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GRADLE_USER_HOME: ./cache
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ hashFiles('build.gradle.kts') }}
      - run: ./gradlew --build-cache dependencies
  test-and-build:
    runs-on: ubuntu-latest
    env:
      GRADLE_USER_HOME: ./cache
    outputs:
      PROJECT_VERSION: ${{ steps.export-env.outputs.PROJECT_VERSION }}
      PROJECT_NAME: ${{ steps.export-env.outputs.PROJECT_NAME }}
      IMAGE_NAME: ${{ steps.export-env.outputs.IMAGE_NAME }}
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ hashFiles('build.gradle.kts') }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew spotlessCheck
      - run: ./gradlew test
      - run: ./gradlew bootJar
      - id: export-env
        run: |
          export PROJECT_VERSION=$(./gradlew properties | grep ^version: | awk '{print $2}')
          export PROJECT_NAME=$(./gradlew properties | grep ^name: | awk '{print $2}')
          export ARTIFACT_NAME=$PROJECT_NAME-$PROJECT_VERSION
          echo PROJECT_VERSION=$PROJECT_VERSION | tee -a $GITHUB_OUTPUT $GITHUB_ENV
          echo PROJECT_NAME=$PROJECT_NAME | tee -a $GITHUB_OUTPUT $GITHUB_ENV
          echo IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$PROJECT_NAME:$PROJECT_VERSION | tee -a $GITHUB_OUTPUT $GITHUB_ENV
      - run: docker build -t $IMAGE_NAME .
      - run: docker push $IMAGE_NAME
  deploy_to_ecs:
    strategy:
      matrix:
        environment: [dev, prod]
    runs-on: ubuntu-latest
    needs: test-and-build
    environment: ${{ matrix.environment }}
    env:
      PROJECT_NAME: ${{ needs.test-and-build.outputs.PROJECT_NAME }}
      PROJECT_VERSION: ${{ needs.test-and-build.outputs.PROJECT_VERSION }}
      IMAGE_NAME: ${{ needs.test-and-build.outputs.IMAGE_NAME }}
      DEPLOYMENT_TYPE: ECS
      CONTAINER_PORT: 8080
      ENVIRONMENT: ${{ matrix.environment }}
      EXPORTED_ENVIRONMENTS: SPRING_ACTIVE_PROFILE, SPRING_APPLICATION_NAME, EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
      DISTRIBUTION_ID: ${{ vars.DISTRIBUTION_ID }}
      ROUTE_KEY: /api/{proxy+}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${{ vars.EUREKA_URL }}
    steps:
      - run: |
          echo "HEALTH_CHECK_COMMAND=curl http://localhost:$CONTAINER_PORT/actuator/health/ping" >> $GITHUB_ENV
          echo "STACK_ID=$PROJECT_NAME-ecsDeploymentStack" >> $GITHUB_ENV
          echo "CONTAINER_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "TASK_FAMILY=$ENVIRONMENT-$PROJECT_NAME-td" >> $GITHUB_ENV
          echo "SERVICE_NAME=$ENVIRONMENT-$PROJECT_NAME-svc" >> $GITHUB_ENV
          echo "SPRING_ACTIVE_PROFILE=$ENVIRONMENT" >> $GITHUB_ENV
          echo "SPRING_APPLICATION_NAME=$ENVIRONMENT-$PROJECT_NAME" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: hoquangnam45/pharmacy-infra
      - uses: ./actions/setup-deployment
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          shopt -s expand_aliases
          alias mvn="./mvnw -Dmaven.repo.local=.mvn"
          npx cdk deploy --require-approval never
      - run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/api/*"